intro2/form_app/urls.py
from django.urls import path
from . import views

app_name = 'form'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('task-list/', views.task_list, name='list'),
]

intro2/form_app2/urls.py
from django.urls import path
from . import views

app_name = 'form2'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('task-list/', views.task_list, name='list'),
]

intro2/form_app_CRUD/urls.py
from django.urls import path
from . import views

app_name = 'form_app_CRUD'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('task-list/', views.task_list, name='task_list'),
    path('update/<int:task_id>/', views.update, name='update'),
    path('delete/<int:task_id>/', views.delete, name='delete'),
]

intro2/inheritance/urls.py
from django.urls import path
from . import views

app_name='inheritance'

urlpatterns = [
    path('1/', views.first, name='first'),
    path('2/', views.second, name='second'),
]

intro2/intro2/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include #przekierowanie do lokalnego urlspatterns

from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('hello1/', views.hello1),
    # path('hello2/', views.hello2),
    # path('hello3/', views.hello3),
    # path('new/', views.new),
    path('new-app/', include('new_app.urls')),
    path('links/', include('links.urls')),
    path('inheritance/', include('inheritance.urls')),
    path('form-app/', include('form_app.urls')),
    path('form-app2/', include('form_app2.urls')),
    path('form-app4/', include('form_app_CRUD.urls')),
]

intro2/links/urls.py
from django.urls import path
from . import views

app_name = 'links'

urlpatterns = [
    path('first/', views.first, name='first'),
    path('2/', views.second, name='second'),
    path('third/<str:x>/', views.third, name='third'),
]

intro2/new_app/urls.py
from django.urls import path
from new_app import views

urlpatterns = [
    # path('', views.hello),
    path('hi/', views.helloB),
    path('bartek/', views.bartek),
    path('ewa/', views.ewa),
    path('fruits/', views.fruits),
    path('<str:name>/<int:age>/', views.display_name),
    path('2/<str:name>/', views.display_name2),
    path('new-year/', views.is_it_newyear),
]

intro2/form_app/models.py
from django.db import models

# Create your models here.

intro2/form_app2/models.py
from django.db import models

# Create your models here.


class Task(models.Model):
    name = models.TextField()

    def __str__(self):
        return f"{self.name}"

intro2/form_app_CRUD/models.py
from django.db import models

# Create your models here.


class Task(models.Model):
    name = models.TextField()

    def __str__(self):
        return f"{self.name}"

intro2/inheritance/models.py
from django.db import models

# Create your models here.

intro2/links/models.py
from django.db import models

# Create your models here.

intro2/new_app/models.py
from django.db import models

# Create your models here.

intro2/form_app/views.py
from django.shortcuts import render

# Create your views here.
TASKS = []


def register(request):

    return render(
        request,
        'form_app/register.html',
    )


def task_list(request):
    task = request.POST.get('task')
    if task:
        TASKS.append(task)

    return render(
        request,
        'form_app/list.html',
        {"tasks": TASKS},
    )

intro2/form_app2/views.py
from django.shortcuts import render
from form_app2.models import Task
# Create your views here.


def register(request):

    return render(
        request,
        'form_app2/register.html'
    )


def task_list(request):

    task = request.POST.get('task')

    if task:
        Task.objects.create(name=task)

    tasks = Task.objects.all()

    return render(
        request,
        'form_app2/task_list.html',
        context={
            "tasks": tasks,
        }
    )

intro2/form_app_CRUD/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, get_object_or_404, redirect
from form_app_CRUD.models import Task
from django.shortcuts import Http404
from django.views.decorators.http import require_http_methods


# Create your views here.


def register(request):
    return render(
        request,
        'form_app_CRUD/register.html',
    )


def task_list(request):

    if request.method == "POST":
        task = request.POST.get('task')

        if task:
            Task.objects.create(name=task)

        return redirect("form_app_CRUD:task_list")

    tasks = Task.objects.all()  # queryset

    return render(
        request,
        'form_app_CRUD/task_list.html',
        context={"tasks": tasks}
    )


def update(request, task_id):

    if request.method == "GET":
        # try:
        #     task = Task.objects.get(pk=task_id)
        # except ObjectDoesNotExist:
        #     raise Http404

        task = get_object_or_404(Task, id=task_id)

        return render(
            request,
            'form_app_CRUD/update.html',
            context={
                'task': task
            }
        )
    if request.method == "POST":
        updated_task = request.POST.get('task')

        if updated_task:
            task = Task.objects.get(pk=task_id)
            task.name = updated_task
            task.save()

        tasks = Task.objects.all()

        # return render(
        #     request,
        #     'form_app_CRUD/task_list.html',
        #     context={"tasks": tasks}
        # )
        return redirect("form_app_CRUD:task_list")


@require_http_methods(["POST"])
def delete(request, task_id):

    task = get_object_or_404(Task, id=task_id)
    task.delete()

    # return render(
    #     request,
    #     'form_app_CRUD/delete.html',
    # )
    return redirect("form_app_CRUD:task_list")

intro2/inheritance/views.py
from django.shortcuts import render

# Create your views here.


def first(request):
    return render(
        request,
        'inheritance/first.html',
    )

def second(request):
    return render(
        request,
        'inheritance/second.html',
    )

intro2/intro2/views.py
from django.shortcuts import HttpResponse
from django.shortcuts import render


#Przyjmuje http request i zwraca http response
def hello1(request):
    return HttpResponse("Hello")


def hello2(request):
    return HttpResponse("<!DOCTYPE html1><html><head></head><body><h3>Hello!</h3></body></head></html>")


def hello3(request):
    return render(request, 'templates/Hello.html')


def new(request):
    return render(request, 'templates/new.html')

intro2/links/views.py
from django.shortcuts import render

# Create your views here.


def first(request):
    return render(
        request,
        'links/first.html',
    )


def second(requests):
    return render(
        requests,
        'links/second.html',
    )


def third(request, x):
    return render(
        request,
        'links/third.html',
        context={"text": x}
    )

intro2/new_app/views.py
from datetime import datetime
from random import shuffle

from django.shortcuts import HttpResponse, render


# Create your views here.


def helloB(request):
    return render(request, 'new_app/helloB.html')


def bartek(request):
    return HttpResponse('Hi, Bartek')


def ewa(request):
    return HttpResponse('Hi, Ewa')


def display_name(request, name, age):
    a_list = [item for item in name]
    shuffle(a_list)
    shuffled_name = ''.join(a_list)
    return HttpResponse(f'Hello, {shuffled_name.title()}! Age {age}')


def display_name2(request, name):
    my = 'Regards!!!'
    return render(
              request,
              'new_app/name.html',
              context={
                  'name': name.title(),
                  'add': my
              }
    )


def is_it_newyear(request):
    """jinja conditions"""
    now = datetime.now()
    is_new_year = now.day == 1 and now.month == 1

    return render(
        request,
        'new_app/is_it_newyear.html',
        {'is_new_year': is_new_year,
        }
    )


def fruits(request):
    """Jinja loops"""

    fruits = ['apple', 'banana', 'grapes', 'cherry']
    return render(
        request,
        'new_app/fruits.html',
        {'fruits': fruits}
    )

intro2/form_app/templates/form_app/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tasks</title>
</head>
<body>
    <h3>Task list</h3>
    <ol>
    {% for task in tasks %}
        <li>{{task}}</li>
    {% endfor %}
    </ol>
</body>
</html>

intro2/form_app/templates/form_app/register.html
<!DOCTYPE html>
<html lang="en" >
<head>
    <meta charset="UTF-8">
    <title>Form</title>
</head>
<body>
    <form action="{% url 'form:list' %}" method="POST">
        {% csrf_token %}
        <input type="text" name="task">
        <input type="submit" value="Zarejstruj">
    </form>
</body>
</html>

intro2/form_app2/templates/form_app2/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>
    <form method="POST" action="{% url 'form2:list' %}">
        {% csrf_token %}
        <input type="text" name="task">
        <input type="submit" value="Save">
    </form>
</body>
</html>

intro2/form_app2/templates/form_app2/task_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Task list</title>
</head>
<body>
    <h3>Task list</h3>
    {% for task in tasks %}
    <ul>
        <li>
            {{ task }}
        </li>
    </ul>
    {% endfor %}
</body>
</html>

intro2/form_app_CRUD/templates/form_app_CRUD/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete</title>
</head>
<body>
Deleted
</body>
</html>

intro2/form_app_CRUD/templates/form_app_CRUD/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add task</title>
</head>
<body>
Add new task:
    <form method="POST" action="{% url 'form_app_CRUD:task_list' %}">
          {% csrf_token %}
    <input type="text" name="task">
    <input type="submit" value="Add">
</body>
</html>

intro2/form_app_CRUD/templates/form_app_CRUD/task_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Task List</title>
</head>
<body>
    <h2>Task List:</h2>
    <h4>Click to update</h4>
        <ul>
            {% for task in tasks %}
                <li>
                    <a href="{% url 'form_app_CRUD:update' task.id %}"> {{ task }}</a>

                </li>
            {% endfor %}
        </ul>


</body>
</html>

intro2/form_app_CRUD/templates/form_app_CRUD/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl"
          crossorigin="anonymous">
</head>
<body style="padding:1%">
    <h3>Modify task no. {{ task.id }}</h3>

    <form method="POST" style="display: inline;">
        {% csrf_token %}
        <input type="text" name="task" value="{{ task }}" class="col-md-1">
        <input type="submit" value="Update" class="btn btn-success">
    </form>

    <form method="POST" action="{% url 'form_app_CRUD:delete' task.id %}" style="display: inline;">
        {% csrf_token %}
        <input type="submit" value="Delete" class="btn btn-danger">
    </form>
</body>
</html>

intro2/inheritance/templates/inheritance/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block body %}{% endblock %}
</body>
</html>

intro2/inheritance/templates/inheritance/first.html
{% extends "inheritance/base.html" %}

{% block title %}First{% endblock %}

{% block body %}
    <h3>First Inheritance</h3>
    <br>
    Go to <a href="{% url 'inheritance:second' %}"</a> second page!
{% endblock %}

intro2/inheritance/templates/inheritance/second.html
{% extends "inheritance/base.html" %}

{% block title %}Second{% endblock %}}

{% block body %}
    <h3>Second Inheritance</h3>
    <br>
    Go to <a href="{% url 'inheritance:first' %}"</a> first page!
{% endblock %}

intro2/links/templates/links/first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>First</title>
</head>
<body>
    <h2>First!</h2>
    <br><br>

    <!--bad solution-->
    <!--Go to <b><a href="/links/second/" >Second page</b>!-->

    Go to <b><a href="{% url 'links:second' %}">Second page</a></b>!
    <br>
    Go to <b><a href="{% url 'links:third' ' abc' %}">Third page</a></b>!

</body>
</html>

intro2/links/templates/links/second.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Second</title>
</head>
<body>
    <h2 style="color: yellow";>Second!</h2>
    <br>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto cum fugit ipsa libero
        nesciunt perferendis rerum sequi. Deleniti ex, facilis, labore laborum minima nulla odit quibusdam
        quisquam similique sint, tenetur.
    <br>
        Go to <b><a href="{% url 'links:first' %}" >First page</a></b>!
    <br>
        Go to <b><a href="{% url 'links:third' 'abcd' %}" >Third page</a></b>!
</body>
</html>

intro2/links/templates/links/third.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Third</title>
</head>
<body>
    <h3>Third</h3>
    <br>
    <div> Text: {{text}}</div>
        Go to <b><a href="{% url 'links:second' %}" >Second page</a></b>!
    <br>
        Go to <a href="{% url 'links:first' %}">First Page</a>
</body>
</html>

intro2/new_app/templates/new_app/fruits.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Fruits</title>
</head>
<body>
    <h3>List of fruits</h3>
    <ul>
    {% for fruit in fruits %}
        <li>{{ fruit }}</li>
        <br>
    {% endfor %}
    </ul>
</body>
</html>

intro2/new_app/templates/new_app/helloB.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hi</title>
</head>
<body>
    <h2>Hello Bartosz!</h2>
    <h2>How are you?</h2>
</body>
</html>

intro2/new_app/templates/new_app/is_it_newyear.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Is it New Year</title>
<!-- bad solution <link rel="stylesheet" href="../../static/new_app/style.css">-->
    <link rel="stylesheet" href="{% static 'new_app/css/style.css' %}">
</head>
<body>

    {% if is_new_year %}
        <h1>TAK</h1>
    {%else %}
        <h1>NIE</h1>
    {% endif %}


</body>
</html>

intro2/new_app/templates/new_app/name.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>name</title>
</head>
<body>
    Hi, {{name}}!
    <br>
    {{add}}
</body>
</html>